import type { GameConfig, Module, Pipe, Door, Circuit, Crew, MaterialType, MaterialConfig, Inventory, PipeType, PipeStatus, MaterialRequirement } from './types';

const materials: Record<MaterialType, MaterialConfig> = {
  parts: {
    name: '零件',
    icon: '🔧',
    description: '通用机械零件，用于管线和设备维修',
    color: 'text-cyan-400',
  },
  oxygen_filter: {
    name: '氧滤芯',
    icon: '🫁',
    description: '氧气过滤芯，维修氧气管线必需',
    color: 'text-blue-400',
  },
  battery: {
    name: '电池',
    icon: '🔋',
    description: '备用电池组，维修电力管线必需',
    color: 'text-yellow-400',
  },
};

const initialInventory: Inventory = {
  parts: 10,
  oxygen_filter: 6,
  battery: 6,
};

const repairMaterialCost: Record<PipeType, Record<PipeStatus, MaterialRequirement>> = {
  oxygen: {
    normal: {},
    damaged: { parts: 1, oxygen_filter: 1 },
    broken: { parts: 2, oxygen_filter: 2 },
  },
  power: {
    normal: {},
    damaged: { parts: 1, battery: 1 },
    broken: { parts: 2, battery: 2 },
  },
};

const modules: Module[] = [
  {
    id: 'engine',
    name: '动力舱',
    type: 'engine',
    position: { x: 50, y: 50, width: 140, height: 100 },
    oxygenLevel: 100,
    safetyLevel: 100,
    hasPower: true,
    hasOxygen: true,
    isSealed: false,
    connectedTo: ['storage', 'cmd'],
    isPowerSource: true,
    weight: 20,
  },
  {
    id: 'storage',
    name: '储藏室',
    type: 'storage',
    position: { x: 50, y: 200, width: 140, height: 80 },
    oxygenLevel: 100,
    safetyLevel: 100,
    hasPower: true,
    hasOxygen: true,
    isSealed: false,
    connectedTo: ['engine', 'living'],
    weight: 10,
  },
  {
    id: 'living',
    name: '生活舱',
    type: 'living',
    position: { x: 50, y: 330, width: 140, height: 100 },
    oxygenLevel: 100,
    safetyLevel: 100,
    hasPower: true,
    hasOxygen: true,
    isSealed: false,
    connectedTo: ['storage', 'lab', 'airlock'],
    isOxygenGenerator: true,
    weight: 25,
  },
  {
    id: 'airlock',
    name: '气闸室',
    type: 'airlock',
    position: { x: 50, y: 480, width: 140, height: 70 },
    oxygenLevel: 100,
    safetyLevel: 100,
    hasPower: true,
    hasOxygen: true,
    isSealed: false,
    connectedTo: ['living'],
    weight: 5,
  },
  {
    id: 'cmd',
    name: '指挥中心',
    type: 'command',
    position: { x: 280, y: 50, width: 180, height: 120 },
    oxygenLevel: 100,
    safetyLevel: 100,
    hasPower: true,
    hasOxygen: true,
    isSealed: false,
    connectedTo: ['engine', 'lab'],
    weight: 30,
  },
  {
    id: 'lab',
    name: '实验室',
    type: 'lab',
    position: { x: 280, y: 220, width: 180, height: 120 },
    oxygenLevel: 100,
    safetyLevel: 100,
    hasPower: true,
    hasOxygen: true,
    isSealed: false,
    connectedTo: ['cmd', 'living'],
    weight: 20,
  },
];

const pipes: Pipe[] = [
  {
    id: 'o2_1',
    type: 'oxygen',
    from: 'living',
    to: 'storage',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 120, y: 330 },
      { x: 120, y: 280 },
    ],
  },
  {
    id: 'o2_2',
    type: 'oxygen',
    from: 'storage',
    to: 'engine',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 120, y: 200 },
      { x: 120, y: 150 },
    ],
  },
  {
    id: 'o2_3',
    type: 'oxygen',
    from: 'living',
    to: 'lab',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 190, y: 380 },
      { x: 280, y: 380 },
      { x: 280, y: 340 },
    ],
  },
  {
    id: 'o2_4',
    type: 'oxygen',
    from: 'lab',
    to: 'cmd',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 370, y: 220 },
      { x: 370, y: 170 },
    ],
  },
  {
    id: 'o2_5',
    type: 'oxygen',
    from: 'living',
    to: 'airlock',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 120, y: 430 },
      { x: 120, y: 480 },
    ],
  },
  {
    id: 'pwr_1',
    type: 'power',
    from: 'engine',
    to: 'cmd',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 190, y: 100 },
      { x: 280, y: 100 },
    ],
  },
  {
    id: 'pwr_2',
    type: 'power',
    from: 'engine',
    to: 'storage',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 120, y: 150 },
      { x: 120, y: 200 },
    ],
  },
  {
    id: 'pwr_3',
    type: 'power',
    from: 'storage',
    to: 'living',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 120, y: 280 },
      { x: 120, y: 330 },
    ],
  },
  {
    id: 'pwr_4',
    type: 'power',
    from: 'cmd',
    to: 'lab',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 370, y: 170 },
      { x: 370, y: 220 },
    ],
  },
  {
    id: 'pwr_5',
    type: 'power',
    from: 'living',
    to: 'airlock',
    status: 'normal',
    damageLevel: 0,
    path: [
      { x: 120, y: 430 },
      { x: 120, y: 480 },
    ],
  },
];

const doors: Door[] = [
  {
    id: 'door_1',
    between: ['engine', 'storage'],
    isOpen: true,
    isSealed: false,
    position: { x: 120, y: 175 },
  },
  {
    id: 'door_2',
    between: ['storage', 'living'],
    isOpen: true,
    isSealed: false,
    position: { x: 120, y: 305 },
  },
  {
    id: 'door_3',
    between: ['living', 'airlock'],
    isOpen: true,
    isSealed: false,
    position: { x: 120, y: 465 },
  },
  {
    id: 'door_4',
    between: ['engine', 'cmd'],
    isOpen: true,
    isSealed: false,
    position: { x: 235, y: 100 },
  },
  {
    id: 'door_5',
    between: ['cmd', 'lab'],
    isOpen: true,
    isSealed: false,
    position: { x: 370, y: 170 },
  },
  {
    id: 'door_6',
    between: ['lab', 'living'],
    isOpen: true,
    isSealed: false,
    position: { x: 280, y: 360 },
  },
];

const circuits: Circuit[] = [
  { id: 'c1', name: '主照明系统', moduleId: 'cmd', isOn: true, priority: 1 },
  { id: 'c2', name: '通讯系统', moduleId: 'cmd', isOn: true, priority: 1 },
  { id: 'c3', name: '生命维持', moduleId: 'living', isOn: true, priority: 1 },
  { id: 'c4', name: '实验设备', moduleId: 'lab', isOn: true, priority: 2 },
  { id: 'c5', name: '推进系统', moduleId: 'engine', isOn: true, priority: 1 },
  { id: 'c6', name: '储物照明', moduleId: 'storage', isOn: true, priority: 3 },
  { id: 'c7', name: '气闸控制', moduleId: 'airlock', isOn: true, priority: 2 },
];

const crew: Crew[] = [
  {
    id: 'crew1',
    name: '陈工程师',
    avatar: '👨‍🔧',
    skills: { repair: 85, electrical: 60, engineering: 90, medical: 30 },
    health: 100,
    maxHealth: 100,
    injury: 0,
    fatigue: 0,
    hypoxia: 0,
    currentModule: 'engine',
    currentTask: null,
    status: 'idle',
  },
  {
    id: 'crew2',
    name: '李医生',
    avatar: '👩‍⚕️',
    skills: { repair: 50, electrical: 40, engineering: 60, medical: 95 },
    health: 100,
    maxHealth: 100,
    injury: 0,
    fatigue: 0,
    hypoxia: 0,
    currentModule: 'living',
    currentTask: null,
    status: 'idle',
  },
  {
    id: 'crew3',
    name: '王指挥官',
    avatar: '👨‍✈️',
    skills: { repair: 70, electrical: 85, engineering: 75, medical: 50 },
    health: 100,
    maxHealth: 100,
    injury: 0,
    fatigue: 0,
    hypoxia: 0,
    currentModule: 'cmd',
    currentTask: null,
    status: 'idle',
  },
  {
    id: 'crew4',
    name: '张科学家',
    avatar: '👩‍🔬',
    skills: { repair: 60, electrical: 75, engineering: 55, medical: 45 },
    health: 100,
    maxHealth: 100,
    injury: 0,
    fatigue: 0,
    hypoxia: 0,
    currentModule: 'lab',
    currentTask: null,
    status: 'idle',
  },
];

export const baseConfig: GameConfig = {
  totalTime: 600,
  eventFrequency: 0.6,
  safetyDecayRate: 1.0,
  baseRepairSpeed: 1.0,
  initialInventory,
  repairMaterialCost,
  materials,
  modules,
  pipes,
  doors,
  circuits,
  crew,
};

export const difficultySettings = {
  easy: { eventFrequency: 0.4, safetyDecayRate: 0.7, totalTime: 900 },
  normal: { eventFrequency: 0.6, safetyDecayRate: 1.0, totalTime: 600 },
  hard: { eventFrequency: 0.8, safetyDecayRate: 1.5, totalTime: 480 },
};
